IMAGE_ubuntu2204 = "bento/ubuntu-22.04"

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  
  machines={
    "ControllerNode" => {:hostname => "Controller", :box => IMAGE_ubuntu2204, :memory => 1024, :cpus => 1},
    "ManagedNode"  => {:hostname => "Managed",  :box => IMAGE_ubuntu2204, :memory => 1024, :cpus => 1}
  }

  #NodeType1 = 3
  #(1..NodeType1).each do |id|
  machines.each do |name, params|
    config.vm.define name do |vm|
      vm.vm.box = params[:box]
      vm.vm.hostname = params[:hostname]
      #vm.vm.network "private_network", ip: "192.168.56.10#{id}"
      vm.vm.network "public_network", type: "dhcp"
      vm.vm.provider "virtualbox" do |v|
        v.name = name
        v.memory = params[:memory]
        v.cpus = params[:cpus]
      end
      vm.vm.provision "shell", path: "bootstrap/#{name}.sh"
    end
  end
end