IMAGE_2204 = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_2204
  config.vm.hostname = "test"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "my_vm"
    vb.memory = 1024
    vb.cpus = 1

    # مسیر ISO که دانلود کردی
    #vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", 0, "--device", 0, "--type", "dvddrive", "--medium", "/home/mahdy/Downloads/ubuntu-24.04.3-live-server-amd64.iso"]
  end

  # شبکه
  #config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.provision :shell, path:"bootstrap.sh"
end
